// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtLSyqOKLC3gGGF_eUh8FXsTZBntSB3l0',
    appId: '1:1040002483968:web:942e6af5b553fa09a095e5',
    messagingSenderId: '1040002483968',
    projectId: 'my-pi-9',
    authDomain: 'my-pi-9.firebaseapp.com',
    storageBucket: 'my-pi-9.firebasestorage.app',
    measurementId: 'G-E2NHMN5JF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0MjmUxlPjMAswqsNC0EUuCuJiyRZWRls',
    appId: '1:1040002483968:android:76d8d03d0be9aadca095e5',
    messagingSenderId: '1040002483968',
    projectId: 'my-pi-9',
    storageBucket: 'my-pi-9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp2xivAm46gihJM2eMPnTFC5m6Ks6itM8',
    appId: '1:1040002483968:ios:19c09bed8aa645e8a095e5',
    messagingSenderId: '1040002483968',
    projectId: 'my-pi-9',
    storageBucket: 'my-pi-9.firebasestorage.app',
    androidClientId: '1040002483968-0dd3qdc9ef5rd6140g8ipsve6o8c7ron.apps.googleusercontent.com',
    iosClientId: '1040002483968-ll4g2mi7i8plsv8iaptc4te433b2n62m.apps.googleusercontent.com',
    iosBundleId: 'com.example.myPi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp2xivAm46gihJM2eMPnTFC5m6Ks6itM8',
    appId: '1:1040002483968:ios:19c09bed8aa645e8a095e5',
    messagingSenderId: '1040002483968',
    projectId: 'my-pi-9',
    storageBucket: 'my-pi-9.firebasestorage.app',
    androidClientId: '1040002483968-0dd3qdc9ef5rd6140g8ipsve6o8c7ron.apps.googleusercontent.com',
    iosClientId: '1040002483968-ll4g2mi7i8plsv8iaptc4te433b2n62m.apps.googleusercontent.com',
    iosBundleId: 'com.example.myPi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtLSyqOKLC3gGGF_eUh8FXsTZBntSB3l0',
    appId: '1:1040002483968:web:e7af7bba43c7901da095e5',
    messagingSenderId: '1040002483968',
    projectId: 'my-pi-9',
    authDomain: 'my-pi-9.firebaseapp.com',
    storageBucket: 'my-pi-9.firebasestorage.app',
    measurementId: 'G-52T2FW1W5B',
  );

}